- become: yes
  hosts: all
  vars_files:
    - vars.yml
  roles:
    - common
    - server
    - media
  post_tasks:
    - name: Restarting the server
      shell: sleep 2 && shutdown -r now "Restarting..."
      async: 1
      poll: 0
      ignore_errors: true
      become: yes
