---
- name: sets the hostname
  hostname: name={{ inventory_hostname }}

- name: update apt cache
  apt: update_cache=yes cache_valid_time=86400

- name: install common packages
  apt: name={{item}} state=present
  with_items:
    - vim
    - git
    - cron
    - tree
    - tmux
    - ruby
    - curl
    - htop
    - iotop
    - nmap
    - unzip
    - openssl
    - automake
    - libssl-dev
    - libusb-dev
    - python
    - python-dev
    - python-pip
    - python3-lxml
    - python-software-properties
    - software-properties-common
    - build-essential
    - dnsutils

- name: install docker
  apt: deb=https://downloads.hypriot.com/docker-hypriot_1.10.3-1_armhf.deb

- name: start docker service
  service: name=docker state=started

- name: vim forever!
  lineinfile: dest=/etc/bash.bashrc line='export EDITOR=$(which vim)' owner=root group=root

- name: setting up ad-blocking hosts
  copy:
    src=hosts.gz
    dest=/tmp/hosts.gz
    owner=root
    mode=0644

- shell: gunzip /tmp/hosts.gz; mv /tmp/hosts /etc/hosts

- name: add hostname in hosts
  lineinfile:
    dest=/etc/hosts
    insertbefore=BOF
    line="127.0.0.1 {{ inventory_hostname }}"

- name: ensure hdd directory exists
  file: path={{ HDD }} state=directory mode=0777

- name: rules to mount hdd
  mount: name={{ HDD }} src='/dev/sda1' fstype=ext4 state=present opts=defaults,nofail,noatime

- name: startup items
  copy: src=rc.local dest=/etc/rc.local owner=root

- name: check existance of hdd dir
  file: path="{{ HDD }}" state=directory mode=0777

- name: try to mount all devices before finishing up
  command: mount -a
