---
- name: add dirs
  file: path="{{ HDD }}{{item}}" state=directory mode=0777
  with_items:
    - "/.watch"
    - "/.downloads"
    - "/.incomplete"
    - "/Movies"
    - "/TVShows"

- name: install subliminal
  apt: name=subliminal state=present
